name: Auto Generate G1 Prediction

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write  # ← ★これが必要！
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Generate G1 Prediction
        run: python3 generate_gemini.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and Push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Actions"
          git add _posts/
          git commit -m "Add daily G1 prediction"
          git push
          
      # ✅ 必ず実行：_postsを含めたJekyllビルドとPagesへのデプロイ
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        if: always()
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v2
